
let kiSession=null,kiProfile=null,kiMode='login',kiSavedOnly=false;
async function kiAuth(path,body){const r=await fetch(SB+'/auth/v1/'+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.msg||d.message||d.error_description||'Алдаа гарлаа');return d}
async function kiApi(path,opt={}){const h={apikey:KEY,'Content-Type':'application/json',...(opt.headers||{})};if(kiSession?.access_token)h.Authorization='Bearer '+kiSession.access_token;const r=await fetch(SB+'/rest/v1/'+path,{...opt,headers:h});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
function kiModal(id,on=true){document.querySelector('#'+id)?.classList.toggle('open',on);document.body.style.overflow=on?'hidden':''}
function kiShowAuth(mode='login'){kiMode=mode;const s=mode==='signup';document.querySelector('#kiAuthTitle').textContent=s?'Бүртгүүлэх':'Нэвтрэх';document.querySelector('#kiName').style.display=s?'block':'none';document.querySelector('#kiSubmit').textContent=s?'Бүртгүүлэх':'Нэвтрэх';document.querySelector('#kiSwitch').textContent=s?'Бүртгэлтэй бол нэвтрэх':'Шинээр бүртгүүлэх';document.querySelector('#kiMsg').textContent='';kiModal('kiAuthModal')}
function kiSwitch(){kiShowAuth(kiMode==='login'?'signup':'login')}
async function kiSubmit(){const email=document.querySelector('#kiEmail').value.trim(),password=document.querySelector('#kiPass').value,name=document.querySelector('#kiName').value.trim(),msg=document.querySelector('#kiMsg');msg.textContent='Түр хүлээнэ үү…';try{let d;if(kiMode==='signup'){d=await kiAuth('signup',{email,password,data:{display_name:name}});if(!d.access_token){msg.textContent='Бүртгэл үүслээ. Имэйлээ баталгаажуулаад нэвтэрнэ үү.';return}}else d=await kiAuth('token?grant_type=password',{email,password});kiSession=d;localStorage.setItem('ki_session',JSON.stringify(d));await kiLoadProfile();kiModal('kiAuthModal',false);loadIdeas()}catch(e){msg.textContent=e.message}}
async function kiLoadProfile(){if(!kiSession?.user)return;try{const p=await kiApi('profiles?select=id,display_name,role,plan&id=eq.'+kiSession.user.id+'&limit=1');kiProfile=p[0]||null}catch(e){}kiRenderUser()}
function kiRenderUser(){const a=document.querySelector('.actions');if(!a)return;if(kiSession){a.innerHTML=(kiProfile?.role==='admin'?'<button class="btn ghost" onclick="kiShowAddMenu()">＋ Нэмэх</button>':'')+'<button class="btn primary" onclick="kiLogout()">Гарах</button>'}else a.innerHTML='<button class="btn ghost" onclick="kiShowAuth(\'login\')">Нэвтрэх</button><button class="btn primary" onclick="kiShowAuth(\'signup\')">Бүртгүүлэх</button>'}
function kiLogout(){kiSession=null;kiProfile=null;kiSavedOnly=false;localStorage.removeItem('ki_session');kiRenderUser();loadIdeas()}
async function kiFav(id,b){if(!kiSession){kiShowAuth();return}try{const ex=await kiApi('favorites?select=idea_id&user_id=eq.'+kiSession.user.id+'&idea_id=eq.'+id);if(ex.length){await kiApi('favorites?user_id=eq.'+kiSession.user.id+'&idea_id=eq.'+id,{method:'DELETE'});b.textContent='♡'}else{await kiApi('favorites',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:kiSession.user.id,idea_id:id})});b.textContent='♥'}}catch(e){console.error(e)}}
function kiSaved(e){e?.preventDefault();if(!kiSession){kiShowAuth();return}kiSavedOnly=true;document.querySelector('#ideas').scrollIntoView({behavior:'smooth'});loadIdeas()}
function kiShowAddMenu(){if(kiProfile?.role!=='admin')return;kiModal('kiAddMenuModal')}
function kiShowAdmin(){if(kiProfile?.role!=='admin')return;kiModal('kiAdminModal')}
function kiOpenWorksheetUpload(){if(kiProfile?.role!=='admin')return;kiModal('kiResourceModal')}

async function kiUploadResource(){
 const msg=document.querySelector('#kiResMsg'),file=document.querySelector('#kiResFile').files[0],title=document.querySelector('#kiResTitle').value.trim();
 if(!file||!title){msg.textContent='Гарчиг болон файл сонгоно уу.';return}
 msg.textContent='Файл байршуулж байна…';
 try{
  const safe=(Date.now()+'-'+file.name).replace(/[^a-zA-Z0-9._-]/g,'-');
  const up=await fetch(SB+'/storage/v1/object/kinderidea-resources/'+safe,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+kiSession.access_token,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});
  if(!up.ok)throw new Error(await up.text());
  const fileUrl=SB+'/storage/v1/object/public/kinderidea-resources/'+encodeURIComponent(safe);
  const body={author_id:kiSession.user.id,title,slug:kiSlug(title),summary:document.querySelector('#kiResSummary').value.trim(),age_group:document.querySelector('#kiResAge').value,category_id:document.querySelector('#kiResCat').value,methodology:document.querySelector('#kiResMethod').value,season:document.querySelector('#kiResSeason').value,content_type:document.querySelector('#kiResType').value,status:document.querySelector('#kiResStatus').value,published_at:document.querySelector('#kiResStatus').value==='published'?new Date().toISOString():null};
  const idea=await kiApi('ideas',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});
  await kiApi('resources',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({idea_id:idea[0].id,title:file.name,file_url:fileUrl,file_type:file.type||file.name.split('.').pop(),is_premium:false})});
  msg.textContent=body.status==='published'?'Нийтлэгдлээ ✓':'Ноорог хадгалагдлаа ✓';
  setTimeout(()=>{kiModal('kiResourceModal',false);loadIdeas()},700)
 }catch(e){msg.textContent='Алдаа: '+e.message}
}
function kiSlug(s){return s.toLowerCase().trim().replace(/[^a-z0-9а-яөүё]+/gi,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36)}
async function kiPublish(){const msg=document.querySelector('#kiAdminMsg');msg.textContent='Нийтэлж байна…';try{const lines=id=>document.querySelector('#'+id).value.split('\n').map(x=>x.trim()).filter(Boolean);const title=document.querySelector('#kiTitle').value.trim();if(!title)throw new Error('Гарчиг оруулна уу');const body={author_id:kiSession.user.id,title,slug:kiSlug(title),summary:document.querySelector('#kiSummary').value.trim(),age_group:document.querySelector('#kiAge').value,category_id:document.querySelector('#kiCat').value,methodology:document.querySelector('#kiMethod').value,season:document.querySelector('#kiSeason').value,content_type:document.querySelector('#kiType').value,learning_outcomes:lines('kiOutcomes'),materials:lines('kiMaterials'),steps:lines('kiSteps').map((x,i)=>({title:'Алхам '+(i+1),text:x})),teacher_tips:document.querySelector('#kiTips').value.trim(),status:document.querySelector('#kiStatus')?.value||'published',published_at:(document.querySelector('#kiStatus')?.value||'published')==='published'?new Date().toISOString():null};await kiApi('ideas',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});msg.textContent='Нийтлэгдлээ ✓';setTimeout(()=>{kiModal('kiAdminModal',false);loadIdeas()},600)}catch(e){msg.textContent='Алдаа: '+e.message}}
async function kiRestore(){try{const s=JSON.parse(localStorage.getItem('ki_session')||'null');if(!s?.access_token)return kiRenderUser();const r=await fetch(SB+'/auth/v1/user',{headers:{apikey:KEY,Authorization:'Bearer '+s.access_token}});if(!r.ok){localStorage.removeItem('ki_session');return kiRenderUser()}s.user=await r.json();kiSession=s;await kiLoadProfile()}catch(e){localStorage.removeItem('ki_session');kiRenderUser()}}
const kiOldLoad=loadIdeas;
loadIdeas=async function(cat=''){const g=document.querySelector('#ideasGrid'),q=document.querySelector('#q').value.trim();g.innerHTML='<div class="empty">Уншиж байна…</div>';try{let p='ideas?select=id,title,summary,age_group,content_type,cover_url,methodology,season&status=eq.published&order=published_at.desc.nullslast';if(age)p+='&age_group=eq.'+age;if(view===2)p+='&content_type=eq.open_lesson';else if(view===1)p+='&content_type=in.(worksheet,visual,game,ppt,document)';if(cat)p+='&category_id=eq.'+cat;const method=document.querySelector('#method')?.value||'',season=document.querySelector('#season')?.value||'';if(method)p+='&methodology=eq.'+method;if(season)p+='&season=eq.'+season;if(q)p+='&or=(title.ilike.*'+encodeURIComponent(q)+'*,summary.ilike.*'+encodeURIComponent(q)+'*)';let d=await api(p);let fav=new Set;if(kiSession){const f=await kiApi('favorites?select=idea_id&user_id=eq.'+kiSession.user.id);fav=new Set(f.map(x=>x.idea_id));if(kiSavedOnly)d=d.filter(x=>fav.has(x.id))}g.innerHTML=d.length?d.map(x=>'<article class="card" onclick="openIdea(\''+x.id+'\')"><div class="cover">'+(x.cover_url?'<img src="'+x.cover_url+'" alt="" style="width:100%;height:100%;object-fit:cover">':'🌈')+'</div><div class="body"><button class="kiHeart" onclick="event.stopPropagation();kiFav(\''+x.id+'\',this)">'+(fav.has(x.id)?'♥':'♡')+'</button><span class="tag">'+(x.age_group?x.age_group+' нас · ':'')+label(x.content_type)+'</span><h3>'+esc(x.title)+'</h3><div class="muted">'+esc(x.summary||'Хэрэгжүүлэхэд бэлэн багшийн санаа')+'</div></div></article>').join(''):'<div class="empty"><b>'+(kiSavedOnly?'Хадгалсан санаа алга.':'Одоогоор санаа алга.')+'</b></div>'}catch(e){g.innerHTML='<div class="empty">Санааны санг ачаалж чадсангүй.</div>';console.error(e)}}
document.addEventListener('DOMContentLoaded',()=>{document.body.insertAdjacentHTML('beforeend',`
<div class="modal" id="kiAuthModal"><div class="modalBox kiSmall"><button class="close" onclick="kiModal('kiAuthModal',false)">✕</button><h2 id="kiAuthTitle">Нэвтрэх</h2><div class="kiForm"><input id="kiName" placeholder="Таны нэр"><input id="kiEmail" type="email" placeholder="Имэйл"><input id="kiPass" type="password" placeholder="Нууц үг (6+ тэмдэгт)"><button class="btn primary" id="kiSubmit" onclick="kiSubmit()">Нэвтрэх</button><div class="kiMsg" id="kiMsg"></div><button class="btn ghost" id="kiSwitch" onclick="kiSwitch()">Шинээр бүртгүүлэх</button></div></div></div>
<div class="modal" id="kiAddMenuModal"><div class="modalBox kiSmall"><button class="close" onclick="kiModal('kiAddMenuModal',false)">✕</button><h2>Юу нэмэх вэ?</h2><div class="kiForm"><button class="btn primary" onclick="kiModal('kiAddMenuModal',false);kiShowAdmin()">💡 Санаа нэмэх</button><button class="btn ghost" onclick="kiModal('kiAddMenuModal',false);kiOpenWorksheetUpload()">📄 Бэлдэц нэмэх</button></div></div></div>
<div class="modal" id="kiAdminModal"><div class="modalBox"><button class="close" onclick="kiModal('kiAdminModal',false)">✕</button><h2>Шинэ санаа нийтлэх</h2><div class="kiForm"><input id="kiTitle" placeholder="Санааны гарчиг"><textarea id="kiSummary" placeholder="Товч тайлбар"></textarea><select id="kiType"><option value="activity">Үйл ажиллагаа</option><option value="worksheet">Бэлдэц / Worksheet</option><option value="visual">Үзүүлэн</option><option value="game">Тоглоомын карт</option><option value="ppt">PPT</option><option value="open_lesson">Нээлттэй хичээл</option><option value="document">Баримт бичиг</option></select><div class="kiTwo"><select id="kiAge"><option value="2-3">2–3 нас</option><option value="3-4">3–4 нас</option><option value="4-5">4–5 нас</option><option value="5-6">5–6 нас</option></select><select id="kiCat"></select></div><div class="kiTwo"><select id="kiMethod"><option value="story">Зохиолд суурилсан</option><option value="play">Тоглоомд суурилсан</option><option value="project">Төсөлд суурилсан</option><option value="inquiry">Шинжлэн судлах</option></select><select id="kiSeason"><option value="all">Бүх улирал</option><option value="spring">Хавар</option><option value="summer">Зун</option><option value="autumn">Намар</option><option value="winter">Өвөл</option></select></div><textarea id="kiOutcomes" placeholder="СҮД — мөр бүрт нэг"></textarea><textarea id="kiMaterials" placeholder="Хэрэглэгдэхүүн — мөр бүрт нэг"></textarea><textarea id="kiSteps" placeholder="Алхам — мөр бүрт нэг"></textarea><textarea id="kiTips" placeholder="Багшид өгөх зөвлөмж"></textarea><select id="kiStatus"><option value="draft">Ноорог хадгалах</option><option value="published">Шууд нийтлэх</option></select><button class="btn primary" onclick="kiPublish()">Хадгалах</button><div class="kiMsg" id="kiAdminMsg"></div></div></div></div>`);
document.querySelectorAll('a').forEach(a=>{if(a.textContent.trim()==='Миний сан')a.onclick=kiSaved});
api('categories?select=id,name&is_active=eq.true&order=sort_order').then(d=>{document.querySelector('#kiCat').innerHTML=d.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')});
document.body.insertAdjacentHTML('beforeend',`
<div class="modal" id="kiResourceModal"><div class="modalBox"><button class="close" onclick="kiModal('kiResourceModal',false)">✕</button><h2>📄 Бэлдэц нэмэх</h2><div class="kiForm"><input id="kiResTitle" placeholder="Бэлдэцийн нэр"><textarea id="kiResSummary" placeholder="Товч тайлбар"></textarea><div class="kiTwo"><select id="kiResType"><option value="worksheet">Worksheet</option><option value="visual">Үзүүлэн</option><option value="game">Тоглоомын карт</option><option value="ppt">PPT</option><option value="document">Баримт бичиг</option></select><select id="kiResAge"><option value="2-3">2–3 нас</option><option value="3-4">3–4 нас</option><option value="4-5">4–5 нас</option><option value="5-6">5–6 нас</option></select></div><select id="kiResCat"></select><div class="kiTwo"><select id="kiResMethod"><option value="play">Тоглоомд суурилсан</option><option value="story">Зохиолд суурилсан</option><option value="project">Төсөлд суурилсан</option><option value="inquiry">Шинжлэн судлах</option></select><select id="kiResSeason"><option value="all">Бүх улирал</option><option value="spring">Хавар</option><option value="summer">Зун</option><option value="autumn">Намар</option><option value="winter">Өвөл</option></select></div><input id="kiResFile" type="file" accept=".png,.jpg,.jpeg,.webp,.pdf,.ppt,.pptx"><select id="kiResStatus"><option value="draft">Ноорог хадгалах</option><option value="published">Шууд нийтлэх</option></select><button class="btn primary" onclick="kiUploadResource()">Файл хадгалах</button><div class="kiMsg" id="kiResMsg"></div></div></div></div>`);
api('categories?select=id,name&is_active=eq.true&order=sort_order').then(d=>{document.querySelector('#kiResCat').innerHTML=d.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('')});
(async()=>{await kiRestore();await loadIdeas()})();
});